### ISSUE TITLE
double无法载入

### ISSUE THREAD

**Issue by devil233-ui** [DoublexQAQ/Yunzai-Bot-Js-Plugin#1]
是不兼容trss？
> 0|TRSS-Yunzai  | [04:47:33.949][ERRO][  TRSSYz  ] [插 件 管 理 器 ]加 载 插 件 < example/Double视 频 插 件 .js/ >错 误 : SyntaxError: Unexpected token (1:0)
> 0|TRSS-Yunzai  |     at pp$4.raise (file:///root/TRSS-Yunzai/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:3640:13)
> 0|TRSS-Yunzai  |     at pp$9.unexpected (file:///root/TRSS-Yunzai/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:766:8)
> 0|TRSS-Yunzai  |     at pp$5.parseExprAtomDefault (file:///root/TRSS-Yunzai/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2984:8)
> 0|TRSS-Yunzai  |     at pp$5.parseExprAtom (file:///root/TRSS-Yunzai/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2979:17)
> 0|TRSS-Yunzai  |     at pp$5.parseExprSubscripts (file:///root/TRSS-Yunzai/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2763:19)
> 0|TRSS-Yunzai  |     at pp$5.parseMaybeUnary (file:///root/TRSS-Yunzai/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2721:17)
> 0|TRSS-Yunzai  |     at pp$5.parseExprOps (file:///root/TRSS-Yunzai/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2649:19)
> 0|TRSS-Yunzai  |     at pp$5.parseMaybeConditional (file:///root/TRSS-Yunzai/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2632:19)
> 0|TRSS-Yunzai  |     at pp$5.parseMaybeAssign (file:///root/TRSS-Yunzai/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2599:19)
> 0|TRSS-Yunzai  |     at pp$5.parseExpression (file:///root/TRSS-Yunzai/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2562:19) {
> 0|TRSS-Yunzai  |   pos: 0,
> 0|TRSS-Yunzai  |   loc: Position { line: 1, column: 0 },
> 0|TRSS-Yunzai  |   raisedAt: 1

![Screenshot_2024-11-22-04-51-23-022_com server auditor ssh client-edit](https://github.com/user-attachments/assets/3160eb57-0f04-43a3-a492-89bca1583f85)

**Comment by DoublexQAQ** [comment]
没给trss做兼容，但是理论上能用

**Comment by DoublexQAQ** [comment]
加群563079037，晚上我修复了给你说

**Comment by DoublexQAQ** [comment]
已发布trss版本的适配插件
